name: Node.js CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
            - name: Install dependencies
              run: npm ci
            - run: npm run build
            - run: npm test -- --passWithNoTests
            - name: Push to build branch
              run: |
                  git ls-remote origin refs/heads/main | grep "^$(git rev-parse HEAD)" || exit 0
                  git checkout -B automated-build
                  mv .git build/.git
                  cd build
                  git add .
                  git config --global user.email ""
                  git config --global user.name "CI"
                  git commit -m"Automatic build"
                  git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git automated-build --force
